name: TESTE PASSWORD
on: 
  workflow_dispatch:
    inputs:
      Senha:
        description: 'Senha'     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.13.0]
        
    steps:
    - uses: actions/checkout@v1
      with:
        SENHA_DEPLOY: ${{github.event.inputs.senha}}
    - name: my-step
      run: echo "Hello World!"
