name: TESTE PASSWORD
on: 
  workflow_dispatch:
    inputs:
      password:
        description: password     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
        
    env:
        github.event.inputs.password: ${{ secrets.INPUTS_PASSWORD }}
    steps:
      - name: my-step
        if: ${{ env.github.event.inputs.password == ${{ secrets.INPUTS_PASSWORD }}
        run: echo "Hello World!"
