name: TESTE PASSWORD
on: 
  workflow_dispatch:
    inputs:
      password:
        description: password     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - if: github.event.inputs.password == ${{ secrets.INPUTS_PASSWORD }}
      uses: actions/checkout@v1
    - name: my-step
      run: echo "Hello World!"
