name: TESTE PASSWORD
on: 
  workflow_dispatch:
    inputs:
      password:
        description: password     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: my-step
      env:
        INPUTS_PASSWORD: ${{ secrets.INPUTS_PASSWORD }}
      if: github.event.inputs.password == 'INPUTS_PASSWORD'
      run: echo "Hello World!"
