name: TESTE PASSWORD
on: 
  workflow_dispatch:
    inputs:
      password:
        description: password     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
       INPUTS_PASSWORD: ${{ secrets.INPUTS_PASSWORD }}

    steps:
    - if: ${{ env.INPUTS_PASSWORD == github.event.inputs.password }}
      run: echo "Hello World!"
