name: TESTE PASSWORD
on: 
  workflow_dispatch:
    inputs:
      password:
        description: password     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.13.0]
        
    steps:
    - uses: actions/checkout@v1
    - name: my-step
      run: echo "Hello World!"
