name: TESTE PASSWORD
on: 
  workflow_dispatch:
    inputs:
      password:
        description: password     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - if: github.event.inputs.password == '123'
      run: echo "Hello World!"
