name: TESTE PASSWORD
on: 
  workflow_dispatch:
    inputs:
      Senha:
        description: 'Log level'     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.13.0]
        
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
    - uses: actions/checkout@v1
    - name: my-step
      run: echo "Hello World!"
