name: TESTE PASSWORD
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.13.0]
        
    steps:
    - uses: actions/checkout@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: my-step
      run: echo "Hello World!"
